prepare:
	@wget https://raw.githubusercontent.com/pviafore/RobustPython/master/code_examples/chapter14/restaurant.yaml \
	      https://raw.githubusercontent.com/pviafore/RobustPython/master/code_examples/chapter14/missing.yaml \
		  https://raw.githubusercontent.com/pviafore/RobustPython/master/code_examples/chapter14/wrong_type.yaml
